color: lime
fieldLayouts:
  1a33aee8-c67e-46f3-9677-56260b2f0143:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-01T20:04:50+00:00'
            elementCondition: null
            fieldUid: a7a91e4f-aa57-4daa-b3a8-375481a6a1ea # Plain Text
            handle: headlineTextPlain
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04adc409-3fe9-476b-802a-6a3fa0e82fb8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-01T20:04:50+00:00'
            elementCondition: null
            fieldUid: 1f2c8908-0a1a-4fb3-8e81-469fa56735aa # Summary
            handle: introTextHtml
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 690b4699-736c-4bb7-93d7-5319b20094ef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-01T20:04:50+00:00'
            elementCondition: null
            fieldUid: a5d4f281-076c-49f2-9c2f-1714a7258fde # Event Types
            handle: null
            includeInCards: false
            instructions: null
            label: 'Event Type Menu'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a29fca41-7159-42d9-946d-00dd51b943d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d9c2d44d-23d9-465a-8aab-d71c2535daae
        userCondition: null
handle: pageHeaderEvents
hasTitleField: false
icon: square
name: 'Page Header (Events)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Page Header (Events)'
titleTranslationKeyFormat: null
titleTranslationMethod: site
