baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'East End Neighborhood Association'
primary: true
siteGroup: d4fc3f26-61fd-490f-8c0c-7aa68f5939c2 # East End Neighborhood Association
sortOrder: 1
