altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b64f0a25-2c81-426d-95b3-2ef6eec11acf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9d6eeb29-bca4-4cb5-a216-66daab949772
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e5e162d-54f5-4a59-99f8-7f96ead68ba7
        userCondition: null
fs: local
handle: blog
name: Blog
sortOrder: 1
subpath: blog
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
