dateModified: 1719152940
email:
  fromEmail: justen@fromsomebodyelse.com
  fromName: 'East End Neighborhood Association'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    955b60b7-99ed-4f91-a916-cdae209841e8: 'East End Neighborhood Association' # East End Neighborhood Association
    d4fc3f26-61fd-490f-8c0c-7aa68f5939c2: 'East End Neighborhood Association' # East End Neighborhood Association
system:
  edition: solo
  live: true
  name: 'East End Neighborhood Association'
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
