defaultPlacement: end
enableVersioning: true
entryTypes:
  - be5e41dc-df3a-434e-a9cc-243df2b9c0a8 # Blog Entry
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  955b60b7-99ed-4f91-a916-cdae209841e8: # East End Neighborhood Association
    enabledByDefault: true
    hasUrls: true
    template: _layouts/page-blog-entry
    uriFormat: 'blog/{slug}'
type: channel
